/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-07 04:52:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/k_digital/spring_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668583483831L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- <html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body> -->\r\n");
      out.write("\r\n");
      out.write(" <!-- main -->\r\n");
      out.write("    <section class=\"main_area\">\r\n");
      out.write("        <article class=\"total_search_area\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <p class=\"main_title\">당신의 영원한 독서문화 공간</p>\r\n");
      out.write("                <div class=\"search_box\">\r\n");
      out.write("                    <!-- 도서 통합검색 -->\r\n");
      out.write("                    <form action=\"\" method=\"\">\r\n");
      out.write("                        <select name=\"search_item\">\r\n");
      out.write("                            <option value=\"search_title\" selected=\"selected\">도서명</option>\r\n");
      out.write("                            <option value=\"search_author\">저자명</option>\r\n");
      out.write("                            <option value=\"search_publisher\">발행처</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <input type=\"text\" placeholder=\"검색어를 입력하세요.\" />\r\n");
      out.write("                        <button type=\"button\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/search_icon.png\" alt=\"돋보기 검색 아이콘\" />\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"particles-js\"></div>\r\n");
      out.write("            <script type=\"text/javascript\" src=\"./resources/js/particles.min.js\"></script>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"notice_area\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <a href=\"#\"><span>Notice</span>가장 최근의 공지사항 제목이 여기에 들어갑니다.공지사항 제목이 여기에 들어갑니다.공지사항 제목이 여기에 들어갑니다.공지사항\r\n");
      out.write("                    제목이\r\n");
      out.write("                    여기에 들어갑니다.공지사항 제목이 여기에 들어갑니다.</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"book_area best_book\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <h2>이번 달 인기 도서</h2>\r\n");
      out.write("                <div class=\"book_inner\">\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/01.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>슬램덩크 리소스-THE FIRST SLAM DUNK re:SOURCE</h4>\r\n");
      out.write("                            <p>이노우에 타케히코</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/02.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>불편한 편의점 2</h4>\r\n");
      out.write("                            <p>김호연</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/03.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>고양이 해결사 깜냥 5 - 편의점을 환하게 밝혀라!</h4>\r\n");
      out.write("                            <p>홍민정</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/04.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>2023 큰별쌤 최태성의 별★별한국사 한국사능력검정시험 심화(1, 2, 3급) 상</h4>\r\n");
      out.write("                            <p>최태성</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/05.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>마법천자문 57</h4>\r\n");
      out.write("                            <p>유대영</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"book_area new_book\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <h2>신착 도서</h2>\r\n");
      out.write("                <div class=\"book_inner\">\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/01.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>슬램덩크 리소스-THE FIRST SLAM DUNK re:SOURCE</h4>\r\n");
      out.write("                            <p>이노우에 타케히코</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/02.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>불편한 편의점 2</h4>\r\n");
      out.write("                            <p>김호연</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/03.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>고양이 해결사 깜냥 5 - 편의점을 환하게 밝혀라!</h4>\r\n");
      out.write("                            <p>홍민정</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/04.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>2023 큰별쌤 최태성의 별★별한국사 한국사능력검정시험 심화(1, 2, 3급) 상</h4>\r\n");
      out.write("                            <p>최태성</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/05.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>마법천자문 57</h4>\r\n");
      out.write("                            <p>유대영</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"book_box\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./resources/assets/images/03.jpg\" alt=\"책 표지\">\r\n");
      out.write("                            <h4>고양이 해결사 깜냥 5 - 편의점을 환하게 밝혀라!</h4>\r\n");
      out.write("                            <p>홍민정</p>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"category_area\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <h2>- 분류별 도서 조회 -</h2>\r\n");
      out.write("                <div class=\"category_box\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>000</span><br />총류</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>100</span><br />철학</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>200</span><br />종교</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>300</span><br />사회과학</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>400</span><br />순수과학</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>500</span><br />기술과학</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>600</span><br />예술</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>700</span><br />언어</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>800</span><br />문학</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <p><span>900</span><br />역사</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        <article class=\"info_area\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("                <div class=\"notice\">\r\n");
      out.write("                    <h2>도서관 소식</h2>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <p>공지사항 최근 5개 까지 노출</p>\r\n");
      out.write("                        <p>2023-00-00</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <p>공지사항 최근 5개 까지 노출</p>\r\n");
      out.write("                        <p>2023-00-00</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <p>공지사항 최근 5개 까지 노출. 제목이 길어지면 이렇게 처리합니다. 제목이 길어지면 이렇게 처리합니다.</p>\r\n");
      out.write("                        <p>2023-00-00</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <p>공지사항 최근 5개 까지 노출. 제목이 길어지면 이렇게 처리합니다. 제목이 길어지면 이렇게 처리합니다.</p>\r\n");
      out.write("                        <p>2023-00-00</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <p>공지사항 최근 5개 까지 노출</p>\r\n");
      out.write("                        <p>2023-00-00</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"time\">\r\n");
      out.write("                    <h2>이용시간 <span>(평일 및 주말 공통)</span></h2>\r\n");
      out.write("                    <p><span>09</span> : <span>00</span>&nbsp;&nbsp;~&nbsp;&nbsp;<span>22</span> : <span>00</span>\r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    <h2>정기휴관일</h2>\r\n");
      out.write("                    <p>※ 매주 월요일, 정부가 지정한 공휴일<br />※ 장서 및 시설 점검 등 관장이 필요하다고 인정하는 날</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>\r\n");
      out.write("	Hello world!  \r\n");
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("<P>  이름은 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.authInfo.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(". </P>\r\n");
      out.write("\r\n");
      out.write("<p> 다른 이름으로는 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserDTO.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".</p>\r\n");
      out.write("\r\n");
      out.write("<p><a href=\"/myapp/user/mylibrary.do\">나의 도서관</a></p>\r\n");
      out.write("<!-- </body>\r\n");
      out.write("</html> -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
